title:              Leituras do João
email:              jpsot.25@gmail.com
description:        Um espaço para comentar sobre o que leio e treinar minha escrita
author:             João Pedro
baseurl:            ""
url:                "https://joaopedwo.github.io"

# Social Profiles
# twitter_username:   
# github_username:    StartBootstrap
# facebook_username:  StartBootstrap
instagram_username: joao_pedwo 
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
